In [ ]:
#!/usr/bin/env python3
import os, glob, random, subprocess, zipfile, shutil
from contextlib import nullcontext

import numpy as np
import git
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, WeightedRandomSampler
from torchvision import datasets, transforms, models
from tqdm import tqdm

from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix

# ================== CONFIG ==================
REPO_NAME = "AI-finalll"
GITHUB_USERNAME = "andee3301"
GITHUB_EMAIL = "hoang.tran230211@vnuk.edu.vn"

# Colab secrets: from google.colab import userdata; GITHUB_PAT = userdata.get("GITHUB_PAT")
try:
    from google.colab import userdata  # type: ignore
    GITHUB_PAT = userdata.get("GITHUB_PAT")
except Exception:
    GITHUB_PAT = os.environ.get("GITHUB_PAT")

REPO_DIR = f"/content/{REPO_NAME}"
MODEL_FILENAME = "best_model.pth"
LOCAL_MODEL_PATH = f"/content/{MODEL_FILENAME}"
REPO_MODEL_PATH = os.path.join(REPO_DIR, MODEL_FILENAME)

KAGGLE_DATASET = "bhaveshmittal/melanoma-cancer-dataset"
DOWNLOAD_DIR = "/content/kaggle_download"
BASE_EXTRACT_DIR = "/content/data/melanoma_kaggle"

SEED = 42
BATCH_SIZE = 48            # if OOM -> 32
EPOCHS_HEAD = 6
EPOCHS_ALL = 25
PATIENCE = 6

LR_HEAD = 3e-4
LR_ALL  = 1e-4
WEIGHT_DECAY = 1e-4
NUM_WORKERS = 2
GRAD_CLIP_NORM = 1.0
LABEL_SMOOTHING = 0.05

USE_COMPILE = False        # turn True only if you really want; compile can complicate debugging


# ================== REPRO ==================
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = True
    torch.backends.cudnn.deterministic = False


# ================== KAGGLE ==================
def ensure_kaggle_json():
    kaggle_dir = os.path.expanduser("~/.kaggle")
    kaggle_path = os.path.join(kaggle_dir, "kaggle.json")
    if os.path.exists(kaggle_path):
        print("✅ kaggle.json already exists.")
        return

    try:
        from google.colab import files  # type: ignore
    except Exception:
        raise FileNotFoundError("kaggle.json not found and not in Colab. Place it at ~/.kaggle/kaggle.json.")

    print("📤 Upload kaggle.json now.")
    uploaded = files.upload()
    if "kaggle.json" not in uploaded:
        raise RuntimeError("❌ kaggle.json not uploaded.")

    os.makedirs(kaggle_dir, exist_ok=True)
    with open(kaggle_path, "wb") as f:
        f.write(uploaded["kaggle.json"])
    os.chmod(kaggle_path, 0o600)
    print("✅ kaggle.json installed.")


def _find_base_with(train_or_test: str, root: str) -> str:
    direct = os.path.join(root, train_or_test)
    if os.path.isdir(direct):
        return root
    for p in glob.glob(os.path.join(root, "*")):
        if os.path.isdir(p) and os.path.isdir(os.path.join(p, train_or_test)):
            return p
    for dirpath, dirnames, _ in os.walk(root):
        if train_or_test in dirnames:
            return dirpath
    raise FileNotFoundError(f"Could not find '{train_or_test}' under {root}")


def prepare_kaggle_dataset():
    ensure_kaggle_json()
    os.makedirs(DOWNLOAD_DIR, exist_ok=True)
    os.makedirs(BASE_EXTRACT_DIR, exist_ok=True)

    print("📥 Downloading dataset from Kaggle...")
    subprocess.run(
        ["kaggle", "datasets", "download", "-d", KAGGLE_DATASET, "-p", DOWNLOAD_DIR, "--force"],
        check=True,
    )

    zips = sorted(glob.glob(os.path.join(DOWNLOAD_DIR, "*.zip")), key=os.path.getmtime, reverse=True)
    if not zips:
        raise FileNotFoundError("No zip found after Kaggle download.")
    zip_path = zips[0]
    print("📦 Extracting:", zip_path)

    # Fresh extract dir each run to avoid weird merges
    if os.path.exists(BASE_EXTRACT_DIR):
        # keep the root dir, but clear contents
        for p in glob.glob(os.path.join(BASE_EXTRACT_DIR, "*")):
            if os.path.isdir(p):
                shutil.rmtree(p)
            else:
                os.remove(p)

    with zipfile.ZipFile(zip_path, "r") as zf:
        zf.extractall(BASE_EXTRACT_DIR)

    base = _find_base_with("train", BASE_EXTRACT_DIR)
    train_dir = os.path.join(base, "train")
    val_dir = os.path.join(base, "test")

    print("✅ Dataset ready:")
    print("Train:", train_dir)
    print("Val  :", val_dir)
    print("Train classes:", os.listdir(train_dir))
    return train_dir, val_dir


# ================== DATA ==================
def create_dataloaders(train_dir, val_dir, batch_size, device):
    # Strong augmentation; you can add MixUp/CutMix later if you want.
    train_tf = transforms.Compose([
        transforms.RandomResizedCrop(224, scale=(0.65, 1.0)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomVerticalFlip(),
        transforms.RandomRotation(25),
        transforms.ColorJitter(0.25, 0.25, 0.25, 0.02),
        transforms.RandomAutocontrast(p=0.25),
        transforms.ToTensor(),
        transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225]),
    ])
    val_tf = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225]),
    ])

    ds_train = datasets.ImageFolder(train_dir, transform=train_tf)
    ds_val = datasets.ImageFolder(val_dir, transform=val_tf)
    class_names = ds_train.classes
    num_classes = len(class_names)

    print("✅ Classes:", class_names)
    targets = np.array(ds_train.targets)
    counts = np.bincount(targets, minlength=num_classes).astype(np.float32)
    print("Train class counts:", counts)

    class_w = 1.0 / (counts + 1e-6)
    class_w = class_w / class_w.mean()   # mean=1.0 for stability

    sample_w = class_w[targets]
    sampler = WeightedRandomSampler(torch.from_numpy(sample_w).double(),
                                   num_samples=len(sample_w),
                                   replacement=True)

    pin = (device.type == "cuda")
    dl_train = DataLoader(ds_train, batch_size=batch_size, sampler=sampler,
                          num_workers=NUM_WORKERS, pin_memory=pin,
                          persistent_workers=(NUM_WORKERS>0))
    dl_val = DataLoader(ds_val, batch_size=batch_size, shuffle=False,
                        num_workers=NUM_WORKERS, pin_memory=pin,
                        persistent_workers=(NUM_WORKERS>0))

    return {"train": dl_train, "val": dl_val}, num_classes, torch.tensor(class_w, dtype=torch.float32), class_names


# ================== MODEL ==================
def build_model(num_classes, device):
    model = models.efficientnet_b2(weights=models.EfficientNet_B2_Weights.DEFAULT)
    in_features = model.classifier[1].in_features
    model.classifier[1] = nn.Linear(in_features, num_classes)
    return model.to(device)


def freeze_backbone_train_head(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = False
    for p in model.classifier.parameters():
        p.requires_grad = True


def unfreeze_all(model: nn.Module):
    for p in model.parameters():
        p.requires_grad = True


def unwrap_if_compiled(model: nn.Module) -> nn.Module:
    return getattr(model, "_orig_mod", model)


def safe_load_state_dict(model: nn.Module, state_dict: dict):
    # handle compiled checkpoints that include _orig_mod. prefix
    if any(k.startswith("_orig_mod.") for k in state_dict.keys()):
        state_dict = {k.replace("_orig_mod.", "", 1): v for k, v in state_dict.items()}
    model.load_state_dict(state_dict, strict=True)


# ================== OPT / SCHED ==================
def make_optimizer(model, lr):
    params = [p for p in model.parameters() if p.requires_grad]
    return optim.AdamW(params, lr=lr, weight_decay=WEIGHT_DECAY)


def make_scheduler(optimizer, steps_per_epoch, epochs):
    return optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=steps_per_epoch * epochs)


def autocast_ctx(device, use_amp):
    if not use_amp:
        return nullcontext()
    return torch.autocast("cuda", dtype=torch.float16)


# ================== EVAL ==================
@torch.no_grad()
def evaluate(model, dataloader, criterion, device, use_amp, class_names):
    model.eval()
    total_loss = 0.0
    all_probs = []
    all_labels = []

    ctx = autocast_ctx(device, use_amp)

    for x, y in tqdm(dataloader, desc="Validating", leave=False):
        x = x.to(device, non_blocking=True)
        y = y.to(device, non_blocking=True)
        with ctx:
            logits = model(x)
            loss = criterion(logits, y)

        total_loss += loss.item() * x.size(0)
        probs = torch.softmax(logits, dim=1).detach().cpu().numpy()
        all_probs.append(probs)
        all_labels.append(y.detach().cpu().numpy())

    all_probs = np.concatenate(all_probs)
    all_labels = np.concatenate(all_labels)
    preds = np.argmax(all_probs, axis=1)

    avg_loss = total_loss / len(dataloader.dataset)
    acc = float((preds == all_labels).mean())

    report = classification_report(all_labels, preds, target_names=class_names, output_dict=True, zero_division=0)
    f1 = report["weighted avg"]["f1-score"]
    prec = report["weighted avg"]["precision"]
    rec = report["weighted avg"]["recall"]

    auc = float("nan")
    try:
        if all_probs.shape[1] == 2:
            auc = roc_auc_score(all_labels, all_probs[:, 1])
    except Exception:
        pass

    cm = confusion_matrix(all_labels, preds)
    return avg_loss, acc, f1, prec, rec, auc, cm


# ================== TRAIN ==================
def train_stage(model, dataloaders, criterion, optimizer, scheduler,
                device, use_amp, class_names, max_epochs, patience, scaler):
    best_loss = float("inf")
    best_state = None
    wait = 0

    ctx = autocast_ctx(device, use_amp)

    for epoch in range(1, max_epochs + 1):
        model.train()
        run_loss = 0.0
        run_correct = 0
        n = 0

        print(f"\n🔥 Epoch {epoch}/{max_epochs} | LR {optimizer.param_groups[0]['lr']:.6f}")

        for x, y in tqdm(dataloaders["train"], desc="Training", leave=False):
            x = x.to(device, non_blocking=True)
            y = y.to(device, non_blocking=True)

            optimizer.zero_grad(set_to_none=True)

            with ctx:
                logits = model(x)
                loss = criterion(logits, y)

            if use_amp:
                scaler.scale(loss).backward()
                scaler.unscale_(optimizer)
                if GRAD_CLIP_NORM is not None:
                    torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP_NORM)
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                if GRAD_CLIP_NORM is not None:
                    torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP_NORM)
                optimizer.step()

            scheduler.step()

            run_loss += loss.item() * x.size(0)
            preds = logits.argmax(dim=1)
            run_correct += (preds == y).sum().item()
            n += x.size(0)

        train_loss = run_loss / n
        train_acc = run_correct / n

        val_loss, val_acc, val_f1, val_prec, val_rec, val_auc, cm = evaluate(
            model, dataloaders["val"], criterion, device, use_amp, class_names
        )

        print(f"Train Loss {train_loss:.4f} | Acc {train_acc:.4f}")
        print(f"Val   Loss {val_loss:.4f} | Acc {val_acc:.4f} | F1 {val_f1:.4f} | Prec {val_prec:.4f} | Rec {val_rec:.4f} | AUC {val_auc:.4f}")
        print("Confusion matrix:\n", cm)

        if val_loss < best_loss:
            best_loss = val_loss
            base = unwrap_if_compiled(model)
            # Save portable weights
            torch.save(base.state_dict(), LOCAL_MODEL_PATH)
            best_state = {k: v.cpu() for k, v in base.state_dict().items()}
            print(f"💾 Saved best -> {LOCAL_MODEL_PATH}")
            wait = 0
        else:
            wait += 1
            print(f"⏳ Early stopping: {wait}/{patience}")
            if wait >= patience:
                print("⛔ Early stopping triggered.")
                break

    return best_loss, best_state


# ================== GIT ==================
def setup_repo():
    if not GITHUB_PAT:
        raise RuntimeError("GITHUB_PAT not found (Colab secrets or env).")

    auth_url = f"https://{GITHUB_USERNAME}:{GITHUB_PAT}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git"

    if os.path.exists(REPO_DIR):
        repo = git.Repo(REPO_DIR)
        try:
            repo.remotes.origin.set_url(auth_url)
            repo.remotes.origin.pull()
        except Exception as e:
            print("⚠️ Could not pull:", e)
    else:
        repo = git.Repo.clone_from(auth_url, REPO_DIR)

    with repo.config_writer() as cfg:
        cfg.set_value("user", "name", GITHUB_USERNAME)
        cfg.set_value("user", "email", GITHUB_EMAIL)

    print("✅ Repo ready:", REPO_DIR)
    return repo, auth_url


def load_github_model_if_exists(model, device):
    if os.path.exists(REPO_MODEL_PATH):
        print("🔄 Loading existing model from GitHub repo...")
        state = torch.load(REPO_MODEL_PATH, map_location="cpu")
        safe_load_state_dict(model, state)
        print("✅ Loaded GitHub model. Continuing training from it.")
    else:
        print("🆕 No model in repo. Starting from ImageNet weights.")
    return model.to(device)


def commit_and_push_model(repo, auth_url, commit_msg="Update best_model.pth"):
    dst = os.path.join(REPO_DIR, MODEL_FILENAME)
    shutil.copy2(LOCAL_MODEL_PATH, dst)

    rel = os.path.relpath(dst, REPO_DIR)
    repo.index.add([rel])
    repo.index.commit(commit_msg)

    repo.remotes.origin.set_url(auth_url)
    repo.remotes.origin.push()
    print("⬆️ Pushed best_model.pth to GitHub.")


# ================== MAIN ==================
def main():
    set_seed(SEED)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    use_amp = (device.type == "cuda")
    print("Device:", device, "| AMP:", use_amp)

    # Data
    train_dir, val_dir = prepare_kaggle_dataset()
    dataloaders, num_classes, class_w, class_names = create_dataloaders(train_dir, val_dir, BATCH_SIZE, device)

    # Repo
    repo, auth_url = setup_repo()

    # Model
    net = build_model(num_classes, device)
    net = load_github_model_if_exists(net, device)

    # (Optional) compile once, AFTER loading
    if USE_COMPILE and device.type == "cuda":
        try:
            net = torch.compile(net)
            print("⚡ torch.compile enabled")
        except Exception as e:
            print("⚠️ torch.compile failed:", e)

    # Loss (class-weighted CE + label smoothing)
    class_w = class_w.to(device)
    criterion = nn.CrossEntropyLoss(weight=class_w, label_smoothing=LABEL_SMOOTHING)

    # AMP scaler (new API)
    scaler = torch.amp.GradScaler("cuda", enabled=use_amp)

    # ---------- Stage 1: train head only ----------
    print("\n=== STAGE 1: Train classifier head ===")
    freeze_backbone_train_head(net)
    opt1 = make_optimizer(net, LR_HEAD)
    sch1 = make_scheduler(opt1, len(dataloaders["train"]), EPOCHS_HEAD)

    best_loss_1, _ = train_stage(
        net, dataloaders, criterion, opt1, sch1, device, use_amp,
        class_names, max_epochs=EPOCHS_HEAD, patience=max(2, PATIENCE//2), scaler=scaler
    )

    # Load best weights into fresh uncompiled model for stage 2 stability
    net2 = build_model(num_classes, device)
    state = torch.load(LOCAL_MODEL_PATH, map_location="cpu")
    safe_load_state_dict(net2, state)
    net2 = net2.to(device)

    if USE_COMPILE and device.type == "cuda":
        try:
            net2 = torch.compile(net2)
            print("⚡ torch.compile enabled (stage 2)")
        except Exception as e:
            print("⚠️ torch.compile failed (stage 2):", e)

    # ---------- Stage 2: fine-tune all ----------
    print("\n=== STAGE 2: Fine-tune all layers ===")
    unfreeze_all(net2)
    opt2 = make_optimizer(net2, LR_ALL)
    sch2 = make_scheduler(opt2, len(dataloaders["train"]), EPOCHS_ALL)

    best_loss_2, _ = train_stage(
        net2, dataloaders, criterion, opt2, sch2, device, use_amp,
        class_names, max_epochs=EPOCHS_ALL, patience=PATIENCE, scaler=scaler
    )

    print(f"\n✅ Finished. Best checkpoint at: {LOCAL_MODEL_PATH}")

    # Push best checkpoint to GitHub (always push; you can add comparison if you want)
    commit_and_push_model(repo, auth_url, commit_msg=f"Update best_model.pth (val_loss={best_loss_2:.4f})")
    print("\n✅ Done.")


if __name__ == "__main__":
    main()


Device: cuda | AMP: True
✅ kaggle.json already exists.
📥 Downloading dataset from Kaggle...
📦 Extracting: /content/kaggle_download/melanoma-cancer-dataset.zip
✅ Dataset ready:
Train: /content/data/melanoma_kaggle/train
Val  : /content/data/melanoma_kaggle/test
Train classes: ['Malignant', 'Benign']
✅ Classes: ['Benign', 'Malignant']
Train class counts: [6289. 5590.]
✅ Repo ready: /content/AI-finalll
🔄 Loading existing model from GitHub repo...
✅ Loaded GitHub model. Continuing training from it.

=== STAGE 1: Train classifier head ===

🔥 Epoch 1/6 | LR 0.000300


Train Loss 0.1628 | Acc 0.9776
Val   Loss 0.2105 | Acc 0.9560 | F1 0.9560 | Prec 0.9563 | Rec 0.9560 | AUC 0.9899
Confusion matrix:
 [[944  56]
 [ 32 968]]
💾 Saved best -> /content/best_model.pth

🔥 Epoch 2/6 | LR 0.000280


Train Loss 0.1616 | Acc 0.9793
Val   Loss 0.2052 | Acc 0.9580 | F1 0.9580 | Prec 0.9581 | Rec 0.9580 | AUC 0.9903
Confusion matrix:
 [[950  50]
 [ 34 966]]
💾 Saved best -> /content/best_model.pth

🔥 Epoch 3/6 | LR 0.000225


Train Loss 0.1610 | Acc 0.9800
Val   Loss 0.2060 | Acc 0.9575 | F1 0.9575 | Prec 0.9577 | Rec 0.9575 | AUC 0.9906
Confusion matrix:
 [[948  52]
 [ 33 967]]
⏳ Early stopping: 1/3

🔥 Epoch 4/6 | LR 0.000150


Train Loss 0.1604 | Acc 0.9799
Val   Loss 0.2062 | Acc 0.9580 | F1 0.9580 | Prec 0.9581 | Rec 0.9580 | AUC 0.9901
Confusion matrix:
 [[949  51]
 [ 33 967]]
⏳ Early stopping: 2/3

🔥 Epoch 5/6 | LR 0.000075


Train Loss 0.1604 | Acc 0.9801
Val   Loss 0.2074 | Acc 0.9585 | F1 0.9585 | Prec 0.9588 | Rec 0.9585 | AUC 0.9904
Confusion matrix:
 [[946  54]
 [ 29 971]]
⏳ Early stopping: 3/3
⛔ Early stopping triggered.

=== STAGE 2: Fine-tune all layers ===

🔥 Epoch 1/25 | LR 0.000100


Train Loss 0.1711 | Acc 0.9767
Val   Loss 0.2228 | Acc 0.9525 | F1 0.9525 | Prec 0.9532 | Rec 0.9525 | AUC 0.9871
Confusion matrix:
 [[933  67]
 [ 28 972]]
💾 Saved best -> /content/best_model.pth

🔥 Epoch 2/25 | LR 0.000100


Train Loss 0.1658 | Acc 0.9778
Val   Loss 0.2175 | Acc 0.9570 | F1 0.9570 | Prec 0.9570 | Rec 0.9570 | AUC 0.9872
Confusion matrix:
 [[953  47]
 [ 39 961]]
💾 Saved best -> /content/best_model.pth

🔥 Epoch 3/25 | LR 0.000098


Train Loss 0.1666 | Acc 0.9773
Val   Loss 0.2106 | Acc 0.9595 | F1 0.9595 | Prec 0.9595 | Rec 0.9595 | AUC 0.9889
Confusion matrix:
 [[957  43]
 [ 38 962]]
💾 Saved best -> /content/best_model.pth

🔥 Epoch 4/25 | LR 0.000096


Train Loss 0.1575 | Acc 0.9816
Val   Loss 0.2224 | Acc 0.9555 | F1 0.9555 | Prec 0.9556 | Rec 0.9555 | AUC 0.9875
Confusion matrix:
 [[947  53]
 [ 36 964]]
⏳ Early stopping: 1/6

🔥 Epoch 5/25 | LR 0.000094


Train Loss 0.1585 | Acc 0.9806
Val   Loss 0.2228 | Acc 0.9510 | F1 0.9510 | Prec 0.9510 | Rec 0.9510 | AUC 0.9846
Confusion matrix:
 [[951  49]
 [ 49 951]]
⏳ Early stopping: 2/6

🔥 Epoch 6/25 | LR 0.000090


Train Loss 0.1529 | Acc 0.9848
Val   Loss 0.2123 | Acc 0.9555 | F1 0.9555 | Prec 0.9555 | Rec 0.9555 | AUC 0.9864
Confusion matrix:
 [[951  49]
 [ 40 960]]
⏳ Early stopping: 3/6

🔥 Epoch 7/25 | LR 0.000086


Train Loss 0.1508 | Acc 0.9863
Val   Loss 0.2126 | Acc 0.9620 | F1 0.9620 | Prec 0.9622 | Rec 0.9620 | AUC 0.9867
Confusion matrix:
 [[952  48]
 [ 28 972]]
⏳ Early stopping: 4/6

🔥 Epoch 8/25 | LR 0.000082


Train Loss 0.1437 | Acc 0.9882
Val   Loss 0.2238 | Acc 0.9575 | F1 0.9575 | Prec 0.9578 | Rec 0.9575 | AUC 0.9851
Confusion matrix:
 [[945  55]
 [ 30 970]]
⏳ Early stopping: 5/6

🔥 Epoch 9/25 | LR 0.000077


Train Loss 0.1389 | Acc 0.9913
Val   Loss 0.2166 | Acc 0.9620 | F1 0.9620 | Prec 0.9620 | Rec 0.9620 | AUC 0.9821
Confusion matrix:
 [[964  36]
 [ 40 960]]
⏳ Early stopping: 6/6
⛔ Early stopping triggered.

✅ Finished. Best checkpoint at: /content/best_model.pth
⬆️ Pushed best_model.pth to GitHub.

✅ Done.
